export { default as Item } from "./item/Item";
export { default as Header } from "./header/Header";
export { default as Footer } from "./footer/Footer";
export { default as Confirm } from "./confirm/Confirm";
export { default as Spinner } from "./spinner/Spinner";
export { default as Product } from "./product/Product";
export { default as Sidebar } from "./sidebar/Sidebar";
export { default as MySelect} from "./myselect/MySelect";
export { default as Manager } from "./user/manager/Manager";
export { default as GoogleMap} from './google-map/GoogleMap';
export { default as Register } from "./user/register/Register";
export { default as EditUser } from "./user/edit-user/EditUser";
export { default as ShowUser } from "./user/show-user/ShowUser";
export { default as InsertProduct } from "./main/InsertProduct";
export { default as EditProduct } from "./editproduct/EditProduct";
export { default as ImageUpload } from "./image-upload/ImageUpload";
export { default as DeleteUser } from "./user/delete-user/DeleteUser";
export { default as AvatarUpload } from "./avatar-upload/AvatarUpload";
export { default as ManufacturersItem } from "./item/ManufacturersItem";
export { default as DeleteProduct } from "./deleteproduct/DeleteProduct";
export { default as ImageUploadSvg } from "./image-upload/ImageUploadSvg";
export { default as InfiniteLoadingUsers } from "./main/InfiniteLoadingUsers";
export { default as InfiniteLoadingProducts } from "./main/InfiniteLoadingProducts";
export { default as InfiniteLoadingManager } from "./user/manager/InfiniteLoadingManager";
